#!/usr/bin/env bash
# Install nginx web server

default_line="server_name _;"
new_line="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo apt-get -y update
sudo apt -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -e "s|$default_line|$new_line|" /etc/nginx/sites-enabled/default

str_old="=404;"
str_new="@newloc;\n\t}\n\n\tlocation @newloc {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n\'est pas une page\";"

sudo sed -i -z "s|$str_old|$str_new|" /etc/nginx/sites-enabled/default

str_old="location / {"
str_new="location / {\n\t\tadd_header X-Served-By \"$(hostname)\";"

sudo sed -i -z "s|$str_old|$str_new|" /etc/nginx/sites-enabled/default

sudo service nginx restart
