#!/usr/bin/env bash
# Install & config HAproxy load balancer server.

sudo apt-get -y update
sudo apt-get -y install haproxy

config_line="\nfrontend my_frontend\n\tbind *:80\n\tdefault_backend alx_backend\n\nbackend alx_backend\n\tbalance roundrobin\n\tserver 321950-web-01 54.197.82.133:80 check\n\tserver 321950-web-02 54.87.180.34:80 check"

sudo echo -e $config_line >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
