#!/usr/bin/env bash
# fix port 80 nginx config

# listen [::]:80 default_server ipv6only=on;
# listen [::]:80 default_server;
# file_path="/etc/nginx/sites-available/default"
apt-get update
apt-get install -y nginx
service nginx start
new_line="listen [::]:80 default_server;"
sed -i "20s/.*/$new_line/" /etc/nginx/sites-available/default
service nginx restart
