#!/usr/bin/env bash
# same thing new way
ed -i 's/[0-9]\+ default_server/80 default_server/' /etc/nginx/sites-enabled/default
service nginx status | grep -q "not running" && echo "nginx is not running"

