#!/usr/bin/env bash
# Bash script that gives you information about the school file.
sf="school"
if [ -e "$sf" ]
then
	echo "school file exists"
	if [ -s "$sf" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$sf" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
